python3 finetune.py --checkpoint /mnt/bn/ai4s-hl/bamboo/hongyi/debug/checkpoints/soqy_final_rg_ens_1_seed_52_fold_3_checkpoint.pt --fold 3 --seed 52 --epoch 4
python3 finetune.py --checkpoint /mnt/bn/ai4s-hl/bamboo/hongyi/debug/checkpoints/soqy_final_rg_ens_1_seed_52_fold_3_checkpoint.pt --fold 3 --seed 52 --epoch 10
python3 finetune.py --checkpoint /mnt/bn/ai4s-hl/bamboo/hongyi/debug/checkpoints/soqy_final_rg_ens_1_seed_52_fold_3_checkpoint.pt --fold 3 --seed 52 --epoch 16
python3 finetune.py --checkpoint /mnt/bn/ai4s-hl/bamboo/hongyi/debug/checkpoints/soqy_final_rg_ens_2_seed_52_fold_3_checkpoint.pt --fold 3 --seed 52 --epoch 4
python3 finetune.py --checkpoint /mnt/bn/ai4s-hl/bamboo/hongyi/debug/checkpoints/soqy_final_rg_ens_2_seed_52_fold_3_checkpoint.pt --fold 3 --seed 52 --epoch 10
python3 finetune.py --checkpoint /mnt/bn/ai4s-hl/bamboo/hongyi/debug/checkpoints/soqy_final_rg_ens_2_seed_52_fold_3_checkpoint.pt --fold 3 --seed 52 --epoch 16
python3 finetune.py --checkpoint /mnt/bn/ai4s-hl/bamboo/hongyi/debug/checkpoints/soqy_final_rg_ens_3_seed_52_fold_3_checkpoint.pt --fold 3 --seed 52 --epoch 4
python3 finetune.py --checkpoint /mnt/bn/ai4s-hl/bamboo/hongyi/debug/checkpoints/soqy_final_rg_ens_3_seed_52_fold_3_checkpoint.pt --fold 3 --seed 52 --epoch 10
python3 finetune.py --checkpoint /mnt/bn/ai4s-hl/bamboo/hongyi/debug/checkpoints/soqy_final_rg_ens_3_seed_52_fold_3_checkpoint.pt --fold 3 --seed 52 --epoch 16
python3 finetune.py --checkpoint /mnt/bn/ai4s-hl/bamboo/hongyi/debug/checkpoints/soqy_final_rg_ens_4_seed_52_fold_3_checkpoint.pt --fold 3 --seed 52 --epoch 4
python3 finetune.py --checkpoint /mnt/bn/ai4s-hl/bamboo/hongyi/debug/checkpoints/soqy_final_rg_ens_4_seed_52_fold_3_checkpoint.pt --fold 3 --seed 52 --epoch 10
python3 finetune.py --checkpoint /mnt/bn/ai4s-hl/bamboo/hongyi/debug/checkpoints/soqy_final_rg_ens_4_seed_52_fold_3_checkpoint.pt --fold 3 --seed 52 --epoch 16